var p = {
  n: [
    'div',
    'span',
    'z-index',
    'specificity',
    'media query',
    'stylesheet',
    'navbar',
    'container',
    'class',
    'id',
    'img',
    'margin',
    'padding',
    'overflow',
    'text-align',
    'SMACSS',
    'header',
    'footer',
    'main',
    'element',
    'section',
    'article',
    'rule',
    'list item',
    'viewport',
    'tag',
    'skeleton',
    'normalize',
    'modernizr',
    'inheritance',
    'border-radius',
    'width',
    'height',
    'max-width',
    'max-height',
    'grid 960',
    'bootstrap',
    'color',
    'background',
    'flexbox',
    'float',
    'display',
    'font-family',
    'font-size',
    'font-weight'
  ],

  adj: [
    'specified',
    'block-level',
    'inline',
    'responsive',
    'singular',
    'semantic',
    'dry',
    'cascading',
    'rule-based',
    'inheritable',
    'hidden',
    'visible',
    'invisible',
    'buried',
    'organized',
    'overridden'
  ],

  hedges: [
    'with CSS3, you have',
    'remember,',
    'you probably didn\'t know this, but',
    'i still can\'t believe my'
  ]
};
