module.exports = {
  n: [
    'div',
    'span',
    'z-index',
    'specificity',
    'media query',
    'stylesheet',
    'navbar',
    'container',
    'class',
    'id',
    'img',
    'margin',
    'padding',
    'overflow',
    'text-align',
    'SMACSS',
    'header',
    'footer',
    'main',
    'element',
    'section',
    'article',
    'rule',
    'list item',
    'viewport',
    'tag',
    'skeleton',
    'normalize',
    'modernizr',
    'inheritance',
    'border-radius',
    'width',
    'height',
    'max-width',
    'max-height',
    'grid 960',
    'bootstrap',
    'color',
    'background',
    'flexbox',
    'float',
    'display',
    'font-family',
    'font-size',
    'font-weight',
    'selector',
    'box',
    'square',
    'decimal',
    'style',
    'cursor',
    'link',
    'child',
    'parent',
    'em',
    'rem',
    'pixel',
    'screen'
  ],

  adj: [
    'specified',
    'block-level',
    'inline',
    'responsive',
    'singular',
    'semantic',
    'dry',
    'cascading',
    'rule-based',
    'inheritable',
    'hidden',
    'visible',
    'invisible',
    'buried',
    'organized',
    'overridden',
    'italic',
    'oblique',
    'normal',
    'small-caps',
    'bolder',
    'bold',
    'auto',
    'vertical',
    'horizontal',
    'flex-based',
    'repeat-x',
    'repeat-y',
    'repeat',
    'no-repeat',
    'dashed',
    'dotted',
    'solid',
    'double',
    'inset',
    'outset',
    'ridge',
    'groove',
    'left',
    'right',
    'static',
    'relative',
    'absolute',
    'top',
    'bottom',
    'centered',
    'inside',
    'outside',
    'child',
    'parent'
  ],

  hedges: [
    'with CSS3, you have',
    'remember,',
    'you probably didn\'t know this, but',
    'i still can\'t believe my'
  ]
};
